name: Publish package version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-package:
    name: Publish package version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install --ignore-engines --frozen-lockfile

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish
